### ISSUE TITLE
Dates on the main pageare not converted to Persian

### ISSUE THREAD

**Issue by Alireza-Naji** [wordpress-parsi/wp-parsidate#99] opened 2021-11-01 08:59 UTC
thanks for updating the plugin. I have 1 issues and 2 suggestion

1. on the home page, the dates are not change and still in english.

url: alirezanaji.com with elementor pro
theme: bazinews theme from zhaket

2. i suggest that for special sales products, it is possible to change the date and numbers in from persian to English. That is a completely independent feature. on some theme's, persian dates, interferes with the RankMath plugin.

3. support ISO 8601 date format for schema markup. some sites setting the date for schema with ISO 8601. please check the possibility of supporting this ISO for schema.  lack of support for standard dates can cause problems with Rich Result. Examples of ISO 8601 and problems:

standard iso8601 uploaddate in schema: sample: 1400-08-01T21:24:50+03:30
standard iso8601 duration in schema: sample: P1Y2M10DT2H30M
variable date format in rankmath, schema, uploaddate : %date(Y-m-d\TH:i:sP)%

problem with invalid time and date in google search console: **"invalid date format"**

url: https://en.wikipedia.org/wiki/ISO_8601

thanks again

**Comment by hamidrezayazdani** [comment] 2022-03-25 21:37
Hi Alireza. thanks for your suggestions.

I did not fully understand. Do you mean that the dates have not been converted to Hijri Shamsi or are not Persian numbers?

And for your first suggestion:
Do you mean scheduled sales? The problem is that the offer section in RankMath schema is not added with the correct format?

for your second suggestion:
Where is the upload date used? If you mean video schema (because you also gave an example of duration), it is better to specify which schema to examine in which plugin.

**Comment by man4toman** [comment] 2023-12-15 17:43
Closed in [#82](https://github.com/wordpress-parsi/wp-parsidate/issues/82)

**Closed as completed by man4toman** 2023-12-15 17:43 UTC
Labels: Enhancement
